### ISSUE TITLE
Popups sometimes crashes

### ISSUE THREAD

**Issue by karolp1993** [morcibacsi/PSAVanCanBridge#1]
Hi. Sometimes it's happened that with open door, popup on the screen blinks, disappear for a moment and appear again. Popups with automatic lighting active or automatic locking active stays even ignition turns off, also displays few times in a row.

**Comment by morcibacsi** [comment]
Meged by Pull request: #2

**Comment by morcibacsi** [comment]
A new implementation was added in d9d2ba00a2c94ccf717438b7a6e44ee08a65ac07 which also should work with type A displays.
