### ISSUE TITLE
OEM Parking Aid on 206

### ISSUE THREAD

**Issue by najdanovicivan** [morcibacsi/PSAVanCanBridge#20]
Will it be possible to have functional OEM parking aid on the display on VAN 206.

From the web I found out there are two variants one that works on VAN (Made by Valeo) and one which works on CAN (Made by Bosch) 

If it's possible to make it work which one is better to get VAN or CAN version

**Comment by morcibacsi** [comment]
I have some code in the project, which should add support to VAN parking aid. It queries the parking aid ECU with diagnostic frames for the distance as it doesn't report that data on the network by default. However it wasn't tested thoroughly, but it worked on my test bench. CAN version wasn't tested. It should work, but even if it doesn't , it shouldn't require too much effort to add support for it (it would also give more reliable information as it wouldn't require hacking around with diag frames). I'll have one somewhere I just didn't have the time yet to make some experiments.
