### ISSUE TITLE
Do you sell those shields?

### ISSUE THREAD

**Issue by saloid** [morcibacsi/PSAVanCanBridge#29]
Hi, thank you for your project. I want to install it into Peugeot 307 CC with android head unit (which expects CAN bus).
Do you have some spare shields (with ESP32 or without)? If so, I'd like to buy one (instead of ordering parts from sifferent places, ordering PCB manufacturing and so on).
Thank you

**Comment by morcibacsi** [comment]
Currently I don't have any boards for sale, but if you just want to keep the control stalk operating, it is enough to have the CAN bus adapter which comes with the Android unit. For Peugeot and Citroen cars this hardware works perfectly: https://www.aliexpress.com/item/1005003413292076.html  You need to select 108. Peugeot206/207/307 from the setting and it should fine: https://youtu.be/MtLH9LZdBNc?t=15
