### ISSUE TITLE
Feature - low washing fluid level indicator

### ISSUE THREAD

**Issue by karolp1993** [morcibacsi/PSAVanCanBridge#4]
If we use sensor like this: https://pl.aliexpress.com/item/32894861981.html

We can make a simple low level of washing fluid indicator. With simple circuit, we can connect signal from sensor to ESP32 gpio input and switches from 0V to 3.3V or vice versa. Then, we can show popup on display, and with using a buzzer, signal a popup. I'm working about it.

**Comment by morcibacsi** [comment]
This would be awesome.

**Comment by Chaozzmax** [comment]
Any upate about this?

**Comment by karolp1993** [comment]
Unfortunately not. I've made first sketch for tests and.. sold a car.

**Comment by morcibacsi** [comment]
Then I guess we can close this one as I don't really have the time for such features. If anyone feels the need of it then later it can be reopened, and can be implemented.
